const tasks = [
  {
    id: "1",
    key: "BUG-101",
    type: "bug",
    severity: "critical",
    title: "Login accepts expired session token",
    assignee: "SD",
    status: "To Do",
    dueDate: "2026-08-12",
    tag: "auth",
  },
  {
    id: "2",
    key: "BUG-097",
    type: "bug",
    severity: "minor",
    title: "Board flickers when a task is moved",
    assignee: "IS",
    status: "To Do",
    dueDate: "2026-08-14",
    tag: "ui",
  },
  {
    id: "3",
    key: "TASK-110",
    type: "task",
    severity: null,
    title: "Set up Express project skeleton",
    assignee: "RV",
    status: "To Do",
    dueDate: "2026-08-09",
    tag: "backend",
  },
  {
    id: "4",
    key: "BUG-102",
    type: "bug",
    severity: "major",
    title: "Delete confirm shows the wrong task title",
    assignee: "SD",
    status: "In Review",
    dueDate: "2026-08-13",
    tag: "board",
  },
  {
    id: "5",
    key: "BUG-095",
    type: "bug",
    severity: "major",
    title: "Duplicate tasks on double-click submit",
    assignee: "RV",
    status: "In Progress",
    dueDate: "2026-08-11",
    tag: "forms",
  },
  {
    id: "6",
    key: "TASK-108",
    type: "task",
    severity: null,
    title: "Draft MongoDB schema for tasks & users",
    assignee: "IS",
    status: "In Progress",
    dueDate: "2026-08-15",
    tag: "db",
  },
  {
    id: "7",
    key: "BUG-098",
    type: "bug",
    severity: "minor",
    title: "Dark mode flashes white on first load",
    assignee: "IS",
    status: "In Review",
    dueDate: "2026-08-16",
    tag: "ui",
  },
  {
    id: "8",
    key: "TASK-101",
    type: "task",
    severity: null,
    title: "Vite scaffold and repo setup",
    assignee: "SD",
    status: "Done",
    dueDate: "2026-08-03",
    tag: "setup",
  },
];

export default tasks;